[package]
name = "bonsol-interface"
version = "0.2.1"
edition = "2021"
publish = false           # Exclude local crates from licensing checks

[features]
on-chain = ["solana-program"]
default = ["solana-sdk", "serde"]
anchor = ["on-chain", "anchor-lang"]
idl-build = ["anchor-lang/idl-build"]

[dependencies]
arrayref = "0.3.6"
base64 = "0.21.2"
bonsol-schema = { path = "../../schemas-rust", version = "0.2.1" }
bytemuck = { version = "1.15.0", features = ["derive"] }
flatbuffers = { workspace = true }
hex = "0.4.3"
paste = "1.0"
serde = { version = "1.0.197", optional = true }
sha3 = "0.10"
solana-program = { workspace = true, optional = true }
solana-sdk = { workspace = true, optional = true }
thiserror = { workspace = true }

[dependencies.anchor-lang]
optional = true
version = ">=0.28"

[dev-dependencies]
