[package]
name = "bonsol-interface"
version.workspace = true
description = "Interface definitions for Bonsol"
authors = ["anagram build team"]
repository = "https://github.com/bonsolcollective/bonsol"
license = "MIT"
edition = "2021"

[features]
on-chain = ["solana-program"]
default = ["solana-sdk", "serde"]

[dependencies]
arrayref = "0.3.6"
bonsol-schema = { workspace = true }
bytemuck = { version = "1.15.0", features = ["derive"] }
flatbuffers.workspace = true
hex = "0.4.3"
num_enum = "0.7.3"
serde = { version = "1.0.197", optional = true }
sha3 = "0.10.8"
solana-program = { workspace = true, optional = true }
solana-sdk = { workspace = true, optional = true }
thiserror = "1.0.57"

[dev-dependencies]
