[package]
name = "bonsol-interface"
version = "0.1.0"
description = "Interface to Bonsol on-chain program instructions, PDA methods and non-flatbuffer types"
authors = ["anagram build team"]
repository = "https://github.com/anagrambuild/bonsol"
license = "MIT"
edition = "2021"

[features]
on-chain = ["solana-program"]
default = ["solana-sdk", "serde"]

[dependencies]
arrayref = "0.3.6"
bytemuck = { version = "1.15.0", features = ["derive"] }
flatbuffers = "24.3.25"
hex = "0.4.3"
serde = { version = "1.0.197", optional = true }
<<<<<<< HEAD
sha3 = "0.10.8"
solana-program = { workspace = true, optional = true }
solana-sdk = { workspace = true, optional = true }
thiserror = { workspace = true }
bonsol-schema.workspace = true
=======
sha3 = "0.10"
solana-program = { version = "1.18.22", optional = true }
solana-sdk = { version = "1.18.22", optional = true }
thiserror = "1.0.57"

bonsol-schema = "0.1.0"
>>>>>>> 7662a85 (chore: prepare bonsol-interface for publishing)

[dev-dependencies]
