repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
    exclude: |
        (?x)^(
            charts/templates/.*|
            .*/templates/.*
        )$
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck

- repo: https://github.com/thoughtworks/talisman
  rev: 'v1.32.1'  # Update me!
  hooks:
  - id: talisman-commit
    entry: cmd --githook pre-commit

- repo: https://github.com/crate-ci/typos
  rev: v1.30.2
  hooks:
  - id: typos

- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint

- repo: local
  hooks:
  - id: untracked-files
    name: Untracked and modified files
    entry: .git/hooks/check_modified_untracked_files.sh
    language: system
    always_run: true
    pass_filenames: false # Doesn't need filenames.
    # require_serial: true # Uncomment if pyright does not work as expected.
    stages: [pre-push]

# Install pre-commit and pre-push hooks on `pre-commit install`.
default_install_hook_types: [pre-commit, pre-push]

# Run hooks on pre-commit for those that don't set a stage.
default_stages: [pre-commit]

# Stop running hooks after the first failure.
fail_fast: true
