[workspace]
members = [ "iop",
  "onchain/channel",
  "onchain/channel-utils", 
  "relay",
  "schemas-rust",
]
exclude = [
  "iop"
]
resolver = "2"

[workspace.dependencies]
solana-program = "=1.17.18"
solana-sdk = "=1.17.18"
thiserror = "1.0.57"
flatbuffers = "23.5.26"
anyhow = "1.0.40"
solana-program-test = "=1.17.18"
solana-rpc-client = "=1.17.18"
solana-rpc-client-api = "=1.17.18"
solana-pubsub-client = "=1.17.18"
solana-transaction-status = "=1.17.18"
risc0-zkvm = { git = "https://github.com/risc0/risc0"}
risc0-core = { git = "https://github.com/risc0/risc0"}
risc0-zkp = { git = "https://github.com/risc0/risc0"}
risc0-groth16 = { git = "https://github.com/risc0/risc0"}
risc0-binfmt = { git = "https://github.com/risc0/risc0"}
risc0-circuit-recursion = { git = "https://github.com/risc0/risc0"}
tokio-test = "0.4.3"

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"
