[workspace]
members = [
  "channel", "relay",
  "schemas-rust",
  "images/simple"
]
resolver = "2"

[workspace.dependencies]
planus = "0.4.0"
solana-program = "1.17.18"
solana-sdk = "1.17.18"
thiserror = "1.0.56"
solana-program-test = "1.17.18"

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"
