
[workspace]
members = [
  "relay",
  "schemas-rust",
  "onchain/channel",
  "onchain/channel-utils"
]
resolver = "2"
[workspace.dependencies]
bytemuck = "1.15.0"
solana-program = {git = "https://github.com/anza-xyz/agave", tag = "v1.18.9"}
solana-sdk = {git = "https://github.com/anza-xyz/agave", tag = "v1.18.9"}
thiserror = "1.0.57"
flatbuffers = "23.5.26"
anyhow = "1.0.40"
solana-program-test = {git = "https://github.com/anza-xyz/agave", tag = "v1.18.9"}
solana-rpc-client = {git = "https://github.com/anza-xyz/agave", tag = "v1.18.9"}
solana-rpc-client-api = {git = "https://github.com/anza-xyz/agave", tag = "v1.18.9"}
solana-pubsub-client = {git = "https://github.com/anza-xyz/agave", tag = "v1.18.9"}
solana-transaction-status = {git = "https://github.com/anza-xyz/agave", tag = "v1.18.9"}
tokio-test = "0.4.3"

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"

