[workspace.metadata.crane]
name = "bonsol"

[workspace]
members = [
  "iop",
  "onchain/channel",
  "onchain/channel-utils",
  "onchain/channel-interface",
  "onchain/example-callback-program",
  "relay",
  "schemas-rust",
  "cli",
  "sdk",
]
resolver = "2"
# Only necessary for nix cargo workspace artifacts to build without warnings.
# The actual crate derivations build using their individual manifest version.
package.version = "0.0.2"

[workspace.dependencies]
solana-sdk = "=1.18.22"
thiserror = "1.0.57"
flatbuffers = "23.5.26"
anyhow = "1.0.40"
solana-program = "=1.18.22"
solana-program-test = "=1.18.22"
solana-rpc-client = "=1.18.22"
solana-rpc-client-api = "=1.18.22"
solana-pubsub-client = "=1.18.22"
solana-transaction-status = "=1.18.22"
solana-cli-config = "=1.18.22"
yellowstone-grpc-client = "=1.15.4"
yellowstone-grpc-proto = "=1.14.2"
risc0-zkvm = { git = "https://github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix", features = [
  "prove",
], default-features = false }
risc0-core = { git = "https://github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix" }
risc0-zkp = { git = "https://github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix" }
risc0-groth16 = { git = "https://github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix" }
risc0-binfmt = { git = "https://github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix" }
risc0-circuit-recursion = { git = "https://github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix" }
risc0-sys = { git = "https:m//github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix" }
tokio-test = "0.4.3"

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"
