[workspace]
members = [ 
  "iop",
  "onchain/channel",
  "onchain/channel-utils", 
  "onchain/channel-interface",
  "onchain/example-callback-program",
  "relay",
  "schemas-rust",
  "cli",
  "sdk"
]
resolver = "2"

[workspace.dependencies]
solana-sdk = "=1.18.16"
thiserror = "1.0.57"
flatbuffers = "23.5.26"
anyhow = "1.0.40"
solana-program = "=1.18.16"
solana-program-test = "=1.18.16"
solana-rpc-client = "=1.18.16"
solana-rpc-client-api = "=1.18.16"
solana-pubsub-client = "=1.18.16"
solana-transaction-status = "=1.18.16"
solana-cli-config = "=1.18.16"
yellowstone-grpc-client = {git = "https://github.com/rpcpool/yellowstone-grpc", tag="v1.15.0+solana.1.18.16"}
yellowstone-grpc-proto = {git = "https://github.com/rpcpool/yellowstone-grpc", tag="v1.15.0+solana.1.18.16" }
risc0-zkvm = { git = "https://github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix", features = ["prove"], default-features = false }
risc0-core = { git = "https://github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix"}
risc0-zkp = { git = "https://github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix"}
risc0-groth16 = { git = "https://github.com/anagrambuild/risc0",branch = "v1.0.1-bonsai-fix"}
risc0-binfmt = { git = "https://github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix"}
risc0-circuit-recursion = { git = "https://github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix"}
risc0-sys = { git = "https:m//github.com/anagrambuild/risc0", branch = "v1.0.1-bonsai-fix"}
tokio-test = "0.4.3"

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"
