{{- if .Values.tester.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bonsol-tester.fullname" . }}
  labels:
    {{- include "bonsol-tester.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tester.replicaCount }}
  selector:
    matchLabels:
      {{- include "bonsol-tester.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.tester.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bonsol-tester.labels" . | nindent 8 }}
        {{- with .Values.tester.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.tester.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml (default (dict) .Values.tester.podSecurityContext) | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml (default (dict) .Values.tester.securityContext) | nindent 12 }}
          image: "{{ .Values.tester.image.repository }}:{{ .Values.tester.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.tester.image.pullPolicy }}
          env:
          - name: KP
            value: {{ .Values.signer.path }}
          - name: RPC_ENDPOINT
            value: "{{ .Values.rpc.url }}/{{ .Values.rpc.token }}"
          - name: SIMPLE_IMAGE
            value: "https://bonsol-public-images.s3.amazonaws.com/simple-68f4b0c5f9ce034aa60ceb264a18d6c410a3af68fafd931bcfd9ebe7c1e42960"
          {{- if and (hasKey .Values.tester "env") (.Values.tester.env) }}
          {{- range $k,$v := .Values.tester.env }}
          - name: {{ $k }}
            value: {{ $v | quote }}
          {{- end }}
          {{- end }}
          {{- if and (hasKey .Values.tester "command") .Values.tester.command }}
          {{- with .Values.tester.command }}
          command:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- else }}
          command:
          - bash
          - -c
          - |
            solana config set --keypair {{ .Values.signer.path }} -u $RPC_ENDPOINT
            bonsol deploy -y -m {{ include "bonsol-tester.manifestPath" . }} -t url --url $SIMPLE_IMAGE 
            while :
            do
              bonsol execute -f {{ include "bonsol-tester.executionReqPath" . }} -x 1000 -m 10000 -w
              sleep 300
            done
          {{- end }}
          resources:
            {{- toYaml (default (dict) .Values.tester.resources) | nindent 12 }}

          volumeMounts:
            - name: key # only works with keypair signer for now
              mountPath: {{ .Values.signer.path }}
              subPath: {{ base .Values.signer.path }}
            - name: infiles
              mountPath: {{ include "bonsol-tester.manifestPath" . }}
              subPath: {{ base (include "bonsol-tester.manifestPath" .) }}
            - name: infiles
              mountPath: {{ include "bonsol-tester.executionReqPath" . }}
              subPath: {{ base (include "bonsol-tester.executionReqPath" .) }}
            {{- with .Values.tester.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: key
          secret:
            secretName: {{ include "bonsol-provernode.fullname" . }}
        - name: infiles
          configMap:
            name: {{ include "bonsol-tester.fullname" . }}
        {{- with .Values.tester.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.tester.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tester.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tester.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
