apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bonsol-provernode.fullname" . }}
  labels:
    {{- include "bonsol-provernode.labels" . | nindent 4 }}
stringData:
  {{ base .Values.signer.path }}:  "{{ .Values.signer.keypair }}"

  {{ base .Values.provernode.config.filename }}: |
    {{- (tpl .Values.provernode.config.values .) | nindent 4 }}
