apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bonsol-node.fullname" . }}
  labels:
    {{- include "bonsol-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bonsol-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bonsol-node.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml (default (dict) .Values.podSecurityContext) | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml (default (dict) .Values.securityContext) | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          command: 
          - /usr/opt/bonsol/relay
          - -f 
          - {{ .Values.config_filename }}
          resources:
            {{- toYaml (default (dict) .Values.resources) | nindent 12 }}
         
          volumeMounts:
            - name: key # only works with keypair signer for now
              mountPath: {{ .Values.signer_config_path }}
              subPath: {{ base .Values.signer_config_path }}
            - name: images
              mountPath:  {{ .Values.risc0_image_folder }}
            - name: config
              mountPath: {{ .Values.config_filename }}
              subPath: {{ base .Values.config_filename }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "bonsol-node.fullname" . }}
        - name: images
          hostPath:
            path: /opt/bonsol/risc0_images/
            type: DirectoryOrCreate
        - name: key
          secret:
            secretName: {{ include "bonsol-node.fullname" . }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
