apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bonsol-node.fullname" . }}
  labels:
    {{- include "bonsol-node.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bonsol-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bonsol-node.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bonsol-node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }} 
          env:
            - name: RUST_LOG
              value: debug
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/opt/bonsol/relay","-f", "/opt/bonsol/config/Node.toml"]
          ports:
            - name: metrics
              containerPort: 9000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: key # only works with keypair signer for now
              mountPath: {{ .Values.signer_config.path | dir }}
            - name: images
              mountPath:  {{ .Values.risc0_image_folder }}
            - name: config
              mountPath: /opt/bonsol/config
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: images
          hostPath:
            path: {{ .Values.risc0_image_folder }}
            type: DirectoryOrCreate
        - name: config
          configMap:
            name: {{ include "bonsol-node.fullname" . }}-config
            key: Node.toml
        - name: key
          secret:
            secretName: {{ include "bonsol-node.fullname" . }}-secrets
            secretKey: signer.json

        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
