apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bonsol-node.fullname" . }}-secrets
  labels:
    {{- include "bonsol-node.labels" . | nindent 4 }}
data:
  signer.json: {{ .Values.signer_config.local_signer_keypair_content | b64enc }}