apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bonsol-node.fullname" . }}
  labels:
    {{- include "bonsol-node.labels" . | nindent 4 }}
stringData:
  {{ base .Values.signer_config_path }}:  "{{ .Files.Get "inputs/signer.json" }}"

  {{ base .Values.config_filename }}: | 
    {{- .Values.config | nindent 4 }}
