[package]
name = "bonsol-cli"
version = "0.0.1"
edition = "2021"
publish = false     # Exclude local crates from licensing checks

[[bin]]
name = "bonsol"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
bonsol-sdk = { path = "../sdk" }
byte-unit = "4.0.19"
cargo_toml = "0.20.3"
clap = { version = "4.4.2", features = ["derive"] }
indicatif = "0.17.8"
object_store = { version = "0.9.1", features = ["aws"] }
risc0-zkvm = { workspace = true }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.104"
shadow-drive-sdk = "0.8.0"
solana-cli-config = { workspace = true }
solana-rpc-client = { workspace = true }
solana-sdk = { workspace = true }
tokio = { version = "1.38.0", features = ["full"] }
