[package]
name = "bonsol-cli"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "bonsol"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
solana-sdk = { workspace = true }
solana-rpc-client = { workspace = true }
solana-cli-config = { workspace = true }
bonsol-sdk = { path = "../sdk" }
cargo_toml = "0.20.3"
serde_json = "1.0.104"
serde = { version = "1.0.197", features = ["derive"] }
risc0-zkvm = { workspace = true }
object_store = {version = "0.9.1", features = ["aws"]}
byte-unit = "4.0.19"
shadow-drive-sdk = "0.8.0"
indicatif = "0.17.8"
tokio = { version = "1.38.0", features = ["full"] }
anyhow = "1.0.86"