[package]
name = "bonsol-cli"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "bonsol"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
solana-sdk = { workspace = true }
solana-rpc-client = { workspace = true }
solana-cli-config = { workspace = true }
bonsol-sdk = { path = "../sdk" }
cargo_toml = "0.20.3"
serde_json = "1.0.104"
serde = { version = "1.0.197", features = ["derive"] }
risc0-binfmt = { workspace = true }
risc0-zkvm = { workspace = true }
object_store = {version = "0.9.1", features = ["aws"]}
byte-unit = "4.0.19"
shadow-drive-sdk = "0.8.0"
indicatif = "0.17.8"
tokio = { version = "1.38.0", features = ["full"] }
anyhow = "1.0.86"
base64 = "0.21.2"
bs58 = "0.4.0"
sha2 = "0.10.6"
num-traits = "0.2.15"
tera = "1.17.1"
bytes = "1.4.0"
reqwest = { version = "0.11.26", features = [
  "gzip",
  "deflate",
  "stream",
  "native-tls-vendored",
] }