// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ChannelInstructionIxType {
  ExecuteV1 = 0,
  DeployV1 = 1,
  ClaimV1 = 2
}
