risc0_image_folder = "/usr/opt/bonsol/risc0_images"
max_input_size_mb = 10
image_download_timeout_secs = 60
input_download_timeout_secs = 60
maximum_concurrent_proofs = 1
max_image_size_mb = 4
image_compression_ttl_hours = 24
env = "dev"
stark_compression_tools_path = "/usr/opt/bonsol/stark/"
[transaction_sender_config]
  Rpc = { rpc_url = "http://solana:8899" }
[signer_config]
  KeypairFile = { path = "/usr/opt/bonsol/keys/signer.json" }
[ingester_config]
  RpcBlockSubscription = { wss_rpc_url = "ws://solana:8900" }