[package]
name = "local-zk-program-server"
edition = "2021"
version = { workspace = true }

[dependencies]
actix-web = "4.10.2"
tokio = {version = "1.44.1", features = ["full"]}

[lints]
workspace = true
