[package]
name = "anagram-bonsol-sdk"
version = "0.0.1"
edition = "2021"

[dependencies]
solana-sdk = { workspace = true }
solana-rpc-client = { workspace = true}
solana-rpc-client-api = { workspace = true }
anagram-bonsol-schema = { path = "../schemas-rust" }
anagram-bonsol-channel-utils = { path = "../onchain/channel-utils", features = ["default"] }
anagram-bonsol-channel-interface = { path = "../onchain/channel-interface", features = ["default"] }
anyhow = "1.0.86"
flatbuffers = {workspace = true}
tokio = "1.36.0"
serde = { version = "1.0.197"}
serde_json = "1.0.104"
bytes = "1.5.0"
async-trait = "0.1.80"
futures-util = "0.3.30"
reqwest = { version = "0.11.26", features = [
  "gzip",
  "deflate",
  "stream",
  "native-tls-vendored",
] }