[package]
name = "bonsol-sdk"
version = "0.0.1"
edition = "2021"
publish = false     # Exclude local crates from licensing checks

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
bonsol-channel-interface = { path = "../onchain/channel-interface", features = [
  "default",
] }
bonsol-channel-utils = { path = "../onchain/channel-utils", features = [
  "default",
] }
bonsol-schema = { path = "../schemas-rust" }
bytes = "1.5.0"
flatbuffers = { workspace = true }
futures-util = "0.3.30"
reqwest = { version = "0.11.26", features = [
  "gzip",
  "deflate",
  "stream",
  "native-tls-vendored",
] }
serde = { version = "1.0.197" }
serde_json = "1.0.104"
solana-rpc-client = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-sdk = { workspace = true }
tokio = "1.36.0"
