[package]
name = "bonsol-schema"
version.workspace = true
description = "Bonsol types and schema definitions"
authors = ["anagram build team"]
repository = "https://github.com/bonsolcollective/bonsol"
license = "MIT"
edition = "2021"
include = [
    "src/**/*",
    "Cargo.toml",
    "build.rs",
    "flatbuffers/**/*"
]
publish = true

[dependencies]
bytemuck = "1.7.2"
flatbuffers = "24.3.25"
num-derive = "0.4"
num-traits = "0.2"
thiserror = "1.0.57"

[lints.rust]
unused_imports = "allow"
