[package]
name = "anagram-bonsol-schema"
version = "0.0.1"
description = "Bonsol types, schema definitions"
authors = ["anagram build team"]
repository = "https://github.com/anagrambuild/bonsol"
license = "MIT"
edition = "2021"

[dependencies]
flatbuffers = "23.5.26"
thiserror = {workspace = true}
serde = "1.0.196"

[lints]
workspace = true
