name: Build container image used in github actions

on:
  workflow_dispatch:

env:
  CONTAINER_IMAGE": "ghcr.io/bonsol-collective/bonsol-ci-env:1.0.0"

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This is a workaround to set github packages as immutable repository
      # No existing image should be owerwritten
      # Don't disable this step

      - name: Check if Tag Exists
        run: |
          if docker manifest inspect ${CONTAINER_IMAGE} > /dev/null 2>&1; then
            echo "ERROR: Image ${CONTAINER_IMAGE} already exists in the registry. Exiting."
            exit 1
          fi

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.github-actions-ci
          platforms: linux/amd64
          push: true
          tags: ${CONTAINER_IMAGE}
          build-args: |
            VERSION=1.0.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
