name: Build and Publish Node Images (CUDA & Standard)
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubicloud-standard-16
    strategy:
      matrix:
        flavor: [standard, cuda]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          docker-images: false
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Set different tags based on whether this is a tag push or main branch push
      - name: Set Docker Tags
        id: docker_tags
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            # For tag releases, use flavor-v{version}
            echo "TAGS=ghcr.io/bonsol-collective/bonsol-node:${{ matrix.flavor }}-${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            # For main branch pushes, use flavor-{commit_sha}
            echo "TAGS=ghcr.io/bonsol-collective/bonsol-node:${{ matrix.flavor }}-${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile.${{ matrix.flavor }}
          tags: ${{ steps.docker_tags.outputs.TAGS }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max