name: Docker Build from Image CI
on:
  push:
    branches:
      - "main"
      - "ci-rework"
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .github/docker
          file: .github/docker/Dockerfile.build
          platforms: linux/amd64
          push: true
          tags: ghcr.io/anagrambuild/bonsol-ci-env:latest
          build-args: |
            VERSION=latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
