name: Lint, Build, Test
on:
  pull_request:
    branches:
      - main
jobs:
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anagrambuild/bonsol-ci-env:latest
      volumes:
        - ${{ github.workspace }}:/workspaces/bonsol
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Format
        run: cargo +nightly fmt --all -- --check
      # - name: Check Clippy
      #   uses: ./.github/tasks/check-clippy
  build:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anagrambuild/bonsol-ci-env:latest
      volumes:
        - ${{ github.workspace }}:/workspaces/bonsol
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build 
        run: cargo check
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anagrambuild/bonsol-ci-env:latest
      volumes:
        - ${{ github.workspace }}:/workspaces/bonsol
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: cargo test
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anagrambuild/bonsol-ci-env:latest
      volumes:
        - ${{ github.workspace }}:/workspaces/bonsol
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: E2E Test
        run: |
          ./validator.sh -r &
          sleep 60
          ./run-node.sh &
          sleep 10
          cargo run -p --release bonsol-tester