name: CI
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
jobs:
  fmt:
    name: Check & Fmt
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anagrambuild/bonsol-ci-env:latest
      volumes:
        - ${{ github.workspace }}:/workspaces/bonsol
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check 
        shell: bash
        run: |
          cargo check --quiet 2> >(tee cout.txt)
          OUT_FILE_CONTENT=$(cat cout.txt)
          echo "OUT_FILE_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$OUT_FILE_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - uses: exercism/pr-commenter-action@v1.5.1
        with:
          github-token: "${{ github.token }}"
          config-file: ".github/comment-templates/check.yaml"
          template-variables: |
            {
              "outcontent": ${{ toJSON(env.OUT_FILE_CONTENT) }},
              "outhash": ${{ hashFiles('cout.txt') }}
            }
      - name: Fmt
        shell: bash
        run: |
          cargo +nightly fmt --all -- --check 1> >(tee fout.txt)
          OUT_FILE_CONTENT=$(cat fout.txt)
          echo "OUT_FILE_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$OUT_FILE_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - uses: exercism/pr-commenter-action@v1.5.1
        with:
          github-token: "${{ github.token }}"
          config-file: ".github/comment-templates/fmt.yaml"
          template-variables: |
            {
              "outcontent": ${{ toJSON(env.OUT_FILE_CONTENT) }},
              "outhash": ${{ hashFiles('fout.txt') }}
            }
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anagrambuild/bonsol-ci-env:latest
      volumes:
        - ${{ github.workspace }}:/workspaces/bonsol
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: cargo test
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anagrambuild/bonsol-ci-env:latest
      volumes:
        - ${{ github.workspace }}:/workspaces/bonsol
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: E2E Test
        run: |
          cargo build-sbf
          cargo build -p bonsol-node
          solana-test-validator \
          --limit-ledger-size 0 \
          --bind-address 0.0.0.0 \
          --rpc-pubsub-enable-block-subscription \
          --bpf-program BoNsHRcyLLNdtnoDf8hiCNZpyehMC4FDMxs6NTxFi3ew target/deploy/bonsol.so \
          --bpf-program exay1T7QqsJPNcwzMiWubR6vZnqrgM16jZRraHgqBGG target/deploy/callback_example.so \
          -r &
          sleep 30
          ./bin/run-node.sh &
          sleep 15
          cargo run -p bonsol-tester 