name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Check & Fmt
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anagrambuild/bonsol-ci-env:latest
      volumes:
        - ${{ github.workspace }}:/workspaces/bonsol
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build 
        run: |
          cargo check
          cargo +nightly fmt --all -- --check
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anagrambuild/bonsol-ci-env:latest
      volumes:
        - ${{ github.workspace }}:/workspaces/bonsol
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: cargo test
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anagrambuild/bonsol-ci-env:latest
      volumes:
        - ${{ github.workspace }}:/workspaces/bonsol
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: E2E Test
        run: |
          cargo build-sbf
          cargo build -p bonsol-node
          solana-test-validator \
          --limit-ledger-size 0 \
          --bind-address 0.0.0.0 \
          --rpc-pubsub-enable-block-subscription \
          --bpf-program BoNsHRcyLLNdtnoDf8hiCNZpyehMC4FDMxs6NTxFi3ew target/deploy/bonsol.so \
          --bpf-program exay1T7QqsJPNcwzMiWubR6vZnqrgM16jZRraHgqBGG target/deploy/callback_example.so \
          -r &
          sleep 30
          ./bin/run-node.sh &
          sleep 15
          cargo run -p bonsol-tester 