name: Pull request workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:

  contents: read
  pull-requests: write
  packages: read

jobs:

   check-formatting:
    name: Check & Format

    runs-on: ubicloud-standard-16

    container:
      image: ghcr.io/bonsol-collective/bonsol-ci-env:latest
      volumes:
        - local:/workspaces/bonsol

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check 
        shell: bash
        id: check
        run: |
          cargo check

      - name: Fmt
        shell: bash
        id: fmt
        run: |
          cargo +nightly fmt --all -- --check

  unit-tests:
    name: Unit Test

    runs-on: ubicloud-standard-16

    container:
      image: ghcr.io/bonsol-collective/bonsol-ci-env:latest
      options: "-it"
      volumes:
        - local:/workspaces/bonsol

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: cargo test -- --nocapture

  call-build-node-container-image:
    permissions:
      contents: read
      packages: write
    uses: bonsol-collective/bonsol/.github/workflows/build-node-containers.yaml@main

