name: Release workflow

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  create-release:

    runs-on: ubuntu-latest

    steps:
      - name: GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
